ProcExecMCP: procexec.tools.processes Namespace Reference
procexec.tools.processes Namespace Reference
Functions
ProcessInfo|None _get_process_info (psutil.Process proc)
list[ProcessInfo] _filter_processes (list[ProcessInfo] processes, str|None name_filter)
list[ProcessInfo] _sort_processes (list[ProcessInfo] processes, ProcessSortBy sort_by)
tuple[list[ProcessInfo], bool] _limit_processes (list[ProcessInfo] processes, int limit)
ListProcessesOutput list_processes (str|None name_filter=None, ProcessSortBy sort_by=ProcessSortBy.CPU, int limit=100, Context|None ctx=None)
bool _validate_process_exists (int pid)
tuple[bool, str] _terminate_process (psutil.Process proc, float timeout_seconds)
tuple[bool, str] _kill_process_forced (psutil.Process proc)
KillProcessOutput kill_process (int pid, bool force=False, float timeout_seconds=5.0, Context|None ctx=None)
Detailed Description
list_processes tool implementation with psutil integration.
Function Documentation
_filter_processes()
list[ProcessInfo] procexec.tools.processes._filter_processes (list[ProcessInfo] processes, str | None name_filter) protected
Filter processes by name (case-insensitive substring match).
Args:
    processes: List of ProcessInfo objects
    name_filter: Name filter string (None = no filtering)
Returns:
    Filtered list of processes
Examples:
    >>> processes = [ProcessInfo(pid=1, name="python.exe", ...),
    ...              ProcessInfo(pid=2, name="chrome.exe", ...)]
    >>> filtered = _filter_processes(processes, "python")
    >>> len(filtered)
    1
Definition at line 93 of file processes.py.
Referenced by list_processes().
_get_process_info()
ProcessInfo | None procexec.tools.processes._get_process_info (psutil.Process proc) protected
Safely get process information with exception handling.
Args:
    proc: psutil.Process instance
Returns:
    ProcessInfo if successful, None if process is inaccessible
Security:
    - Handles NoSuchProcess (process terminated during iteration)
    - Handles AccessDenied (insufficient permissions)
    - Handles ZombieProcess (defunct process)
    - Sanitizes command line to prevent information leakage
Examples:
    >>> proc = psutil.Process(1234)
    >>> info = _get_process_info(proc)
    >>> print(info.name, info.cpu_percent)
    'python.exe' 2.5
Definition at line 19 of file processes.py.
Referenced by list_processes().
_kill_process_forced()
tuple[bool, str] procexec.tools.processes._kill_process_forced (psutil.Process proc) protected
Forcefully kill a process (SIGKILL/TerminateProcess).
This is the most aggressive termination method and should be used
only when graceful termination fails.
Args:
    proc: psutil.Process instance to kill
Returns:
    Tuple of (success: bool, message: str)
Examples:
    >>> proc = psutil.Process(1234)
    >>> success, msg = _kill_process_forced(proc)
    >>> print(success, msg)
    True 'Process killed forcefully'
Definition at line 372 of file processes.py.
Referenced by kill_process().
_limit_processes()
tuple[list[ProcessInfo], bool] procexec.tools.processes._limit_processes (list[ProcessInfo] processes, int limit) protected
Limit number of processes returned and indicate if truncated.
Args:
    processes: List of ProcessInfo objects
    limit: Maximum number to return
Returns:
    Tuple of (limited process list, truncated flag)
Examples:
    >>> processes = [ProcessInfo(...) for _ in range(200)]
    >>> limited, truncated = _limit_processes(processes, 100)
    >>> len(limited)
    100
    >>> truncated
    True
Definition at line 163 of file processes.py.
Referenced by list_processes().
_sort_processes()
list[ProcessInfo] procexec.tools.processes._sort_processes (list[ProcessInfo] processes, ProcessSortBy sort_by) protected
Sort processes by specified criteria.
Args:
    processes: List of ProcessInfo objects
    sort_by: Sort criterion (cpu, memory, pid, name)
Returns:
    Sorted list of processes
Sorting Rules:
    - cpu: Descending (highest CPU first)
    - memory: Descending (most memory first)
    - pid: Ascending (lowest PID first)
    - name: Ascending (alphabetical)
Examples:
    >>> processes = [ProcessInfo(pid=2, name="b", cpu_percent=5.0, ...),
    ...              ProcessInfo(pid=1, name="a", cpu_percent=10.0, ...)]
    >>> sorted_procs = _sort_processes(processes, ProcessSortBy.CPU)
    >>> sorted_procs[0].cpu_percent
    10.0
Definition at line 124 of file processes.py.
Referenced by list_processes().
_terminate_process()
tuple[bool, str] procexec.tools.processes._terminate_process (psutil.Process proc, float timeout_seconds) protected
Attempt graceful process termination with timeout.
Sends SIGTERM (Unix) or WM_CLOSE (Windows) and waits for process to exit.
Args:
    proc: psutil.Process instance to terminate
    timeout_seconds: Maximum time to wait for termination
Returns:
    Tuple of (success: bool, message: str)
Examples:
    >>> proc = psutil.Process(1234)
    >>> success, msg = _terminate_process(proc, 5.0)
    >>> print(success, msg)
    True 'Process terminated gracefully'
Definition at line 329 of file processes.py.
Referenced by kill_process().
_validate_process_exists()
bool procexec.tools.processes._validate_process_exists (int pid) protected
Check if a process with the given PID exists.
Args:
    pid: Process ID to check
Returns:
    True if process exists, False otherwise
Examples:
    >>> _validate_process_exists(1)
    True
    >>> _validate_process_exists(999999)
    False
Definition at line 311 of file processes.py.
Referenced by kill_process().
kill_process()
KillProcessOutput procexec.tools.processes.kill_process (int pid, bool force = False, float timeout_seconds = 5.0, Context | None ctx = None)
Terminate a process by PID with graceful or forced termination.
This tool allows terminating stuck or hung processes to clean up system
resources. It supports both graceful termination (SIGTERM/WM_CLOSE) with
a timeout, and forced termination (SIGKILL/TerminateProcess) for
unresponsive processes.
Args:
    pid: Process ID to terminate (must be >= 1)
    force: If True, forcefully kill the process. If False, attempt
           graceful termination with timeout. Default: False
    timeout_seconds: Timeout in seconds to wait for graceful termination.
                    Ignored if force=True. Range: 0.1-30.0s. Default: 5.0s
    ctx: MCP context for logging (optional)
Returns:
    KillProcessOutput with success status, PID, message, timing, and
    whether forced termination was used
Raises:
    SanitizedError: If process termination fails or is not enabled
Security:
    - Requires PROCEXEC_ENABLE_KILL=true environment variable to function
    - Handles permission errors gracefully (no crashes)
    - Cannot terminate system-critical processes (OS protection)
    - Error messages are sanitized (no sensitive info)
Examples:
    >>> # Graceful termination
    >>> result = await kill_process(pid=1234, force=False, timeout_seconds=5.0)
    >>> print(result.success, result.message)
    True 'Process terminated gracefully'
    >>> # Forced termination
    >>> result = await kill_process(pid=5678, force=True)
    >>> print(result.success, result.forced)
    True True
Definition at line 421 of file processes.py.
References _kill_process_forced(), _terminate_process(), and _validate_process_exists().
list_processes()
ListProcessesOutput procexec.tools.processes.list_processes (str | None name_filter = None, ProcessSortBy sort_by = ProcessSortBy.CPU, int limit = 100, Context | None ctx = None)
List running processes with optional filtering and sorting.
This tool retrieves information about running processes on the system,
including PID, name, CPU usage, memory usage, command line, and status.
Results can be filtered by name, sorted by various criteria, and limited
to a maximum number of results.
Args:
    name_filter: Filter processes by name (case-insensitive substring match).
                If None, return all processes.
    sort_by: Sort processes by: cpu (descending), memory (descending),
            pid (ascending), or name (ascending). Default: cpu.
    limit: Maximum number of processes to return. Default: 100, max: 1000.
    ctx: MCP context for logging (optional)
Returns:
    ListProcessesOutput with process list, total count, truncation flag,
    and retrieval time
Raises:
    SanitizedError: If process iteration fails
Security:
    - Handles permission errors gracefully (skips inaccessible processes)
    - No sensitive system information leaked in errors
    - Command lines are included but may be empty if access denied
    - Zombie and terminated processes handled without errors
Performance:
    - Uses psutil.process_iter() for efficient iteration
    - oneshot() context for batch info retrieval per process
    - Target: <2s for process list retrieval
Examples:
    >>> result = await list_processes()
    >>> print(result.total_count, "processes found")
    245 processes found
    >>> result = await list_processes(
    ...     name_filter="python",
    ...     sort_by=ProcessSortBy.MEMORY,
    ...     limit=50
    ... )
    >>> for proc in result.processes:
    ...     print(f"{proc.name}: {proc.memory_mb}MB")
Definition at line 190 of file processes.py.
References _filter_processes(), _get_process_info(), _limit_processes(), and _sort_processes().