ProcExecMCP: procexec.tools.execute Namespace Reference
procexec.tools.execute Namespace Reference
Functions
list[str] _parse_command_to_args (str command)
Path|None _validate_working_directory (str|None working_dir)
tuple[str, bool] _enforce_output_limit (str output, int max_bytes)
tuple[str, str, int, bool] _execute_subprocess (list[str] args, Path|None cwd, float timeout_seconds, bool capture_output)
ExecuteCommandOutput execute_command (str command, str|None working_directory=None, int timeout_ms=30000, bool capture_output=True, Context|None ctx=None)
Detailed Description
execute_command tool implementation with security measures.
Function Documentation
_enforce_output_limit()
tuple[str, bool] procexec.tools.execute._enforce_output_limit (str output, int max_bytes) protected
Enforce output size limit to prevent memory exhaustion.
Args:
    output: Output string to check
    max_bytes: Maximum allowed bytes
Returns:
    Tuple of (potentially truncated output, was_truncated)
Examples:
    >>> _enforce_output_limit("short", 1000)
    ('short', False)
    >>> _enforce_output_limit("x" * 2000, 1000)
    ('x' * 1000 + '\\n[Output truncated...]', True)
Definition at line 80 of file execute.py.
Referenced by execute_command().
_execute_subprocess()
tuple[str, str, int, bool] procexec.tools.execute._execute_subprocess (list[str] args, Path | None cwd, float timeout_seconds, bool capture_output) protected
Execute command via subprocess with security measures.
Args:
    args: Command arguments list
    cwd: Working directory or None
    timeout_seconds: Timeout in seconds
    capture_output: Whether to capture stdout/stderr
Returns:
    Tuple of (stdout, stderr, exit_code, timed_out)
Raises:
    SanitizedError: If command execution fails
Security:
    - NEVER uses shell=True
    - Enforces timeout
    - Handles all exception types
    - Sanitizes error messages
Definition at line 111 of file execute.py.
Referenced by execute_command().
_parse_command_to_args()
list[str] procexec.tools.execute._parse_command_to_args (str command) protected
Parse command string into argument list for safe subprocess execution.
Uses shlex.split() with posix=True to properly remove quotes from arguments.
This works correctly on both Windows and Unix platforms.
Args:
    command: Command string to parse
Returns:
    List of command arguments
Security:
    - Uses shlex.split instead of manual parsing
    - posix=True removes quotes from arguments (correct behavior for subprocess)
    - Results in argument list for subprocess.run (no shell=True)
Examples:
    >>> _parse_command_to_args("python --version")
    ['python', '--version']
    >>> _parse_command_to_args('echo "hello world"')
    ['echo', 'hello world']
    >>> _parse_command_to_args('python -c "print(\'test\')"')
    ['python', '-c', "print('test')"]
Definition at line 16 of file execute.py.
Referenced by execute_command().
_validate_working_directory()
Path | None procexec.tools.execute._validate_working_directory (str | None working_dir) protected
Validate working directory if provided.
Args:
    working_dir: Working directory path or None
Returns:
    Validated Path object or None
Raises:
    SanitizedError: If directory validation fails
Definition at line 56 of file execute.py.
Referenced by execute_command().
execute_command()
ExecuteCommandOutput procexec.tools.execute.execute_command (str command, str | None working_directory = None, int timeout_ms = 30000, bool capture_output = True, Context | None ctx = None)
Execute a command safely with timeout and output limits.
This tool executes commands without shell injection vulnerabilities.
Commands are parsed into argument lists and executed directly via
subprocess without shell=True.
Args:
    command: Command to execute (e.g., "python --version", "npm test")
    working_directory: Working directory for execution (default: current)
    timeout_ms: Timeout in milliseconds (default: 30000, max: 300000)
    capture_output: Whether to capture stdout/stderr (default: True)
    ctx: MCP context for logging (optional)
Returns:
    ExecuteCommandOutput with stdout, stderr, exit code, and timing
Raises:
    ValueError: If input validation fails
    SanitizedError: If command execution fails
Security:
    - No shell=True (prevents shell injection)
    - Command parsed with shlex.split (safe parsing)
    - Mandatory timeout enforcement
    - Output size limits (prevents memory exhaustion)
    - Path validation for working directory
    - Sanitized error messages (no information leakage)
Examples:
    >>> result = await execute_command("python --version")
    >>> print(result.stdout)  # "Python 3.11.5"
    >>> print(result.exit_code)  # 0
    >>> result = await execute_command(
    ...     "npm test",
    ...     working_directory="./myproject",
    ...     timeout_ms=60000
    ... )
Definition at line 188 of file execute.py.
References _enforce_output_limit(), _execute_subprocess(), _parse_command_to_args(), and _validate_working_directory().